//jika diperlukan untuk mengubah PORT yang tadinya 8080 menjadi 3000 (Opsional)
runtime: nodejs18
env: standard

instance_class: F2

handlers:
  - url: /.*
    script: auto

env_variables:
  PORT: 3000
